language: java
sudo: required
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
script:
  - ./gradlew test build

after_success:
   - codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml